Fail gracefully if -f is misused

diff --git a/bumpspec b/bumpspec
--- a/bumpspec
+++ b/bumpspec
@@ -33,8 +33,14 @@ while [[ $# -ne 0 ]]; do
 
     case "$1" in
         "-f")
-            specfile="$2"
-            shift 2
+            if [[ $# -ge 2 ]]; then
+                specfile="$2"
+                shift 2
+                continue
+            fi
+            echo "-f: missing argument" 1>&2
+            usage
+            exit 1
             ;;
         "-r")
             bumpminor=yes
